# This is the connection used if no other VaultConnection resources are loaded into the cluster
# For more configuration options, go to https://developer.hashicorp.com/vault/docs/platform/k8s/vso/helm
defaultVaultConnection:
  enabled: true
  address: "https://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: false
controller:
  manager:
    clientCache:
      persistenceModel: direct-encrypted # Encrypted using the Vault Transit engine
      storageEncryption:
        enabled: true
        mount: vault-operator-auth
        keyName: vso-client-cache
        namespace: vault-operator
        transitMount: vault-operator-transit
        kubernetes:
          role: vault-operator-role
          serviceAccount: vault-operator
